FROM alpine:3.15.0 AS fat32

ARG ARCH
ARG NANOOS_VERSION
ARG KERNEL_VERSION
ARG BUSYBOX_VERSION

ENV ARCH=$ARCH
ENV NANOOS_VERSION=$NANOOS_VERSION
ENV KERNEL_VERSION=$KERNEL_VERSION
ENV BUSYBOX_VERSION=$BUSYBOX_VERSION

ADD build-fat32.sh /build/build.sh
ADD LICENSE /build/LICENSE
ADD kernel.tar.gz /build/kernel
ADD busybox.tar.gz /build/busybox
ADD nanoos.efi /build
RUN apk add util-linux-misc dosfstools
ENTRYPOINT sh -c /build/build.sh